### ISSUE TITLE
Sensitive query string

### ISSUE THREAD

**Issue by Xocix** [aws/aws-xray-sdk-dotnet#201]
Hi!

I am trying to figure out if it is possible to hide sensitive query string when running Xray with a .net core web api project and i cant seem to find anything by looking in the code, but maybe i am missing something? 

I see that other language SDK's had similar issues:
https://github.com/aws/aws-xray-sdk-node/issues/246
https://github.com/aws/aws-xray-sdk-go/issues/227

Basically what i am trying to do is alter the Http dictionary and clean it if an url with query string exists when hitting a endpoint.
My setup is the simplest usage in Startup:
```       
public Startup(IConfiguration configuration)
{
    Configuration = configuration;
    AWSXRayRecorder.InitializeInstance(configuration);
}
.....
public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
{
    app.UseXRay("AppName");
}
```

**Comment by srprash** [comment]
Hi @Xocix 
Sorry, I'm a bit confused as to which HTTP request are we concerned about here. Given the other issues you've linked I believe you are looking to strip off the query parameters from the _outgoing_ HTTP requests and not from the _incoming_ HTTP request to your application. Is that right?

**Comment by AnuragMohapatra** [comment]
Hi @srprash 

The issue seems to point to the fact that when a HTTP Get or Post call is made to a 3rd pary API using username or password on query string or token on query string, AWS XRay(with HttpXrayTracing enabled) just records it in plain text rather than masking or stripping it, for example - 

![image](https://user-images.githubusercontent.com/8456793/181417904-c66eeaaa-7c62-4a59-a540-455863b47341.png)

You can see it has actually recorded the api-key being provided to the 3rd party api for authentication, same is the case for username password provided to generate a token, and passing token to authenticate the calls.

This is a risk since api calls can have PII details on query string as well (Apis have not been migrated yet or still follow old model).
