### ISSUE TITLE
UdpSegmentEmitter throws Message too long 

### ISSUE THREAD

**Issue by emmekappa** [aws/aws-xray-sdk-dotnet#29]
Sometimes happens that the buffer to sent to xray deamon exceed the maximum udp packet size.

As result it throws a 
`Failed to send package through socket. --> System.Net.Sockets.SocketException (0x80004005): Message too long`

**Comment by awssandra** [comment]
Hi emmekappa,

We see this on very heavy segments. UPD packet size is about 65kb (IPv4), which is why you're seeing that error.
We have the concept of a streaming subsegment threshold. When a certain number of subsegments are reached, we prune your segment document of the closed subsegment trees, allowing smaller data chunks to be sent to the daemon. Right now, the .Net SDK is hardcoded to 100 subsegments. We have a backlog item to add this as configuration option.
Sorry for the trouble, we'll get this in as soon as we can.

Thanks,
Sandra

**Comment by yogiraj07** [comment]
This feature is merged to [mainline](https://github.com/aws/aws-xray-sdk-dotnet/commit/f41ad03fbec63b63a246bf76e4748c5fe346cadf). Pending release.

**Comment by srprash** [comment]
Hi @emmekappa ,
This feature has been released in v2.7.0
Please refer to the [Changelog](https://github.com/aws/aws-xray-sdk-dotnet/blob/master/CHANGELOG.md) for details.

Thanks,
Prashant
