### ISSUE TITLE
aws x ray entity does not exist in async local

### ISSUE THREAD

**Issue by Akshayvb09** [aws/aws-xray-sdk-dotnet#32]
While executing all tests at a time aws x-ray performing weird. 
Its throwing exception as "**Entity does not exist in async local**". I'm not sure but it can be due to missing traceId at AWSXRayRecorder initialization, check the code below

`public static AWSXRayRecorder XrayRecorderInstance
        {
            get
            {
                if (xrayRecorder != null)
                {
                    return xrayRecorder;
                }
                else
                {
                    lock (threadLock)
                    {
                        if (xrayRecorder == null)
                        {
                            xrayRecorder = new AWSXRayRecorder
                            {
                                ContextMissingStrategy = Amazon.XRay.Recorder.Core.Strategies.ContextMissingStrategy.LOG_ERROR
                                
                            };
                            Amazon.XRay.Recorder.Handlers.AwsSdk.AWSSDKHandler.RegisterXRayForAllServices();
                            return xrayRecorder;
                        }
                        else
                        {
                            return xrayRecorder;
                        }
                    }
                }
            }
        }`

**do I need to add segment here?How? Please help me to resolve this issue.**

**Comment by yogiraj07** [comment]
Hi @Akshayvb09 ,
`Amazon.XRay.Recorder.Handlers.AwsSdk.AWSSDKHandler.RegisterXRayForAllServices();` registers all AWS SDK clients you create in the application with X-Ray SDK. 
This middleware creates `Subsegment` for each AWS SDK call. When a `Subsegment`  is created, the SDK expects `Segment` is already created before this call and present in the `TraceContext`.

The above exception says that X-Ray SDK middleware was trying to create `Subsegment`, however could not find already started `Segment`.
You would need to wrap AWS SDK call around `Segment` in order to succeed.

Something similar to:
```
AWSXRayRecorder.Instance.BeginSegment("test");
ddb.PutItem(); // your AWS SDK call
AWSXRayRecorder.Instance.EndSegment();
```

Reference: https://github.com/aws/aws-xray-sdk-dotnet/blob/master/sdk/test/UnitTests/AWSSdkTracingHandlerTests.cs#L241

Please let me know if you have questions.

Thanks,
Yogi

**Comment by yogiraj07** [comment]
Hi @Akshayvb09 ,
Feel free to reopen this issue if you have any questions.

Best,
Yogi
