### ISSUE TITLE
JsonSegmentMarshaller ctor throws System.IndexOutOfRangeException

### ISSUE THREAD

**Issue by rudygt** [aws/aws-xray-sdk-dotnet#37]
Hi, I'm getting this issue running xunit integration tests in parallel 

![image](https://user-images.githubusercontent.com/1120692/42104634-96845aea-7b8a-11e8-9d99-18ea73bd6112.png)

after a quick google search seems like the exception is being thrown because Dictionary is not thread safe on add. 

looking at the code seems like the crashing one is in this call

https://github.com/aws/aws-xray-sdk-dotnet/blob/master/sdk/src/Core/ThirdParty/LitJson/JsonMapper.cs#L914

and if we swap the dictionaries used on JsonMapper for ConcurrentDictionary it may resolve the issue, or just adding another lock to avoid this particular case. 

https://github.com/aws/aws-xray-sdk-dotnet/blob/master/sdk/src/Core/ThirdParty/LitJson/JsonMapper.cs#L134

let me know if you would take a pull request, 

Regards.

**Comment by yogiraj07** [comment]
Hi @rudygt ,
Thank you for the post.
Could you please help me to reproduce the issue (eg: link to integration tests integrated using `xUnit`)
Also can you please let me know your motivation behind using `xUnit` test framework instead of the provided `MSTest` framework?

Thanks,
Yogi

**Comment by rudygt** [comment]
Hi @yogiraj07 , sorry if I didn't explain myself, 

I'm using the xray recorder on a project of mine, in that project I'm using aspnetcore, I'm using xunit to run my integration tests and to speed things up I execute them with the parallel setting enabled. 

every now and then I see this exception thrown. 

I will try to create an isolated test to reproduce this issue so you can have a better idea. 

thanks!

**Comment by srprash** [comment]
Hi @rudygt ,
Thanks for providing the code to reproduce your issue. However, looking at the `DoLoop()` method, I am unable to understand the reason for testing the `JsonSegmentMarshaller`. When testing the `JsonSegmentMarshaller` directly, it is possible to run into threading issues since the underlying implementation may not be thread-safe. Therefore, `JsonSegmentMarshaller` should not be used directly, as it is managed by [`AWSXRayRecorder Instance`](https://github.com/aws/aws-xray-sdk-dotnet/blob/master/sdk/src/Core/AWSXRayRecorder.cs#L65) which itself is thread-safe. 
I would request you to update the `AWSXRayRecorder` package to the latest version. Feel free to re-open this issue and reach to us if you have any trouble with this.

Best,
Prashant.
