### ISSUE TITLE
First segment in XRay dashboard show wrong client_ip

### ISSUE THREAD

**Issue by jazztong** [aws/aws-xray-sdk-dotnet#45]
When I used XRay SDK in non WAF environment, it showed the correct client_ip in XRay tracing dashboard, but when it tracing in the production environment in WAF integrate, its display the WAF IP in client_ip instead of true client IP, in raw data of tracing, the first segment display WAF IP. but the subsegment displays the correct client IP.

**Comment by awssandra** [comment]
Hi jazztong,

Sorry for the late reply. Can you post a raw snippet showing your resultant trace? Also, how are you utilizing WAF in your AWS stack?

**Comment by jazztong** [comment]
![image](https://user-images.githubusercontent.com/15000126/50130499-e2927d80-02b8-11e9-901a-5189ed617472.png)
![image](https://user-images.githubusercontent.com/15000126/50130605-546ac700-02b9-11e9-8f3d-883c86f4eb2e.png)

Hi awssandra,

WAF was setup as first protection for the request flow, 47.91.54.141 was the WAF IP, but the actual clientIp is 111.65.58.217, as forward IP list, there are multiple IP, I think XRay SDK should use trueIP or lastIP instead of first IP which is WAF IP.

**Comment by yogiraj07** [comment]
Hi @jazztong ,
When a request is forwarded from WAF, the X-Ray SDK parses `X-Forwarded-For` header and gets source ip by design. Please refer [documentation](https://docs.aws.amazon.com/xray/latest/devguide/xray-sdk-dotnet-messagehandler.html) : section `Forwarded Requests`.

Hence, you see WAF client ip on `Segment`. 

If you would like to record true client ip, you can add [Annotation/Metadata](https://github.com/aws/aws-xray-sdk-dotnet/tree/master#adding-metadataannotations-net-and-net-core)

Please let me know if you have more questions.

Thanks,
Yogi

**Comment by yogiraj07** [comment]
Hi @jazztong ,
Please feel free to reopen this issue if you have any questions.

Thanks,
Yogi
