### ISSUE TITLE
SQL Errors Not Recorded Correctly

### ISSUE THREAD

**Issue by jaredcnance** [aws/aws-xray-sdk-dotnet#55]
When an error occurs it is displayed as a different service named "remote" even though it is actually the same database. I believe this is because the SQL information is not collected until after the call is executed. From what I can tell, there is no reason this can't be collected before the call. Additionally, we may be able to collect more information from the SQL Exception if we catch it.

https://github.com/aws/aws-xray-sdk-dotnet/blob/663ab0714ad80da378ebd9694af59534a0de6f36/sdk/src/Handlers/SqlServer/TraceableSqlCommand.netstandard.cs#L426-L428

Example stack trace:

```
SqlException: Timeout expired.  The timeout period elapsed prior to completion of the operation or the server is not responding.at System.Data.SqlClient.SqlConnection.OnError
at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning
at System.Data.SqlClient.TdsParser.TryRun
at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData
at System.Data.SqlClient.SqlDataReader.get_MetaData
at System.Data.SqlClient.SqlCommand.FinishExecuteReader
at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds
at System.Data.SqlClient.SqlCommand.ExecuteReader
at Amazon.XRay.Recorder.Handlers.SqlServer.TraceableSqlCommand.Intercept
```

![image](https://user-images.githubusercontent.com/13851721/52882587-06d5d380-311d-11e9-9f00-f56c47cb4c65.png)

**Comment by yogiraj07** [comment]
Hi @jaredcnance ,
Can you explain a bit more. If these 2 calls are to same database, I had expect 2 subsegments generating same subsegment [name](https://github.com/aws/aws-xray-sdk-dotnet/blob/master/sdk/src/Handlers/SqlServer/TraceableSqlCommand.netstandard.cs#L423). Any exception thrown is recorded on the [Subsegment](https://github.com/aws/aws-xray-sdk-dotnet/blob/master/sdk/src/Handlers/SqlServer/TraceableSqlCommand.netstandard.cs#L434). Please let me know how to reproduce this locally, since I can see only one node for SQL database when any error occurs?

**Comment by yogiraj07** [comment]
Hi @jaredcnance ,
Please feel free to reopen this issue. I am happy to work with you on this.
