### ISSUE TITLE
Entity doesn't exist in AsyncLocal exception

### ISSUE THREAD

**Issue by okubiak** [aws/aws-xray-sdk-dotnet#69]
Hi,

I'm currently working with ASP.NET Core 2.1 and AWSXRayRecorder 2.5.0.
I think that something is missing (at least a better exception) about using aws services outside a http request.

Here is a quick sample to reproduce the issue:

```
        public Startup(IConfiguration configuration)
        {
            AWSXRayRecorder.InitializeInstance(configuration);
            AWSSDKHandler.RegisterXRayForAllServices();
        }

        public void Configure(IApplicationBuilder app, IHostingEnvironment env)
        {
            app.UseXRay("sample");
            Test().GetAwaiter().GetResult();
        }

        private static async Task Test()
        {
            var s3 = new AmazonS3Client(new AnonymousAWSCredentials(), RegionEndpoint.USEast1);
            await s3.GetObjectAsync("testBucket", "testKey");
        }
```
When using RegisterXRayForAllServices(), from my point of view, something is missing when using a service without adding BeginSegment() and EndSegment() around it.
If you're initializing a library or anything else which is calling a aws service, it will throw an exception.

I didn't test yet but we probably have the same issue with a BackgroundService if we miss adding a new Segment.

What's your opinion about it?

**Comment by jaybyrrd** [comment]
Hi there, you need to begin a Segment before you can start tracing subsegments (I believe that is your issue). So before you call Test(), call 

```csharp
AWSXRayRecorder.Instance.StartSegment("someName");
```
After that you will need to call 

```csharp
AWSXRayRecorder.Instance.EndSegment();
```

That's my suspicion in terms of the problem you are facing. Assuming you are running an ASP.NET Application, you will not need to start and end segments manually on any of your controllers/endpoints as the UseXray call handles that for you.

**Comment by okubiak** [comment]
Yes, sorry if I wasn't clear, but as I said I know why this sample is crashing. :)
But do we really want to do that?
Maybe I don't want to trace this call (for any reasons or because the S3 call is something done in an external library).
ASP.NET app are not only controllers app and aws services can be called outside of tracked http requests.
Using this RegisterXRay require to add lot of Segments (or a global one in the BackgroundService).

**Comment by jaybyrrd** [comment]
Sorry, I jumped to how to fix it. That's on me. 

So I think the premise is that the s3 or service call isn't a full segment on its own, it is a subsegment, and so the expectation is that in your console app you determine the logic that dictates the beginning and end of the parent segment and the aws service providers adopt that.

If you aren't dictating the beginning and end of segments, then you aren't tracing your actual software.

**Comment by yogiraj07** [comment]
Hi @okubiak ,
 `AWSSDKHandler` generates `Subsegment` around AWS SDK call and expects `Segment` in the `TraceContext`.  Above code snippet generates `Subsegment` out side HTTP request and hence `Segment` which `app.UseXRay()` generates is not available.

@jaybyrrd explanation is correct. 

1. You would need to identify entry point of your background service and create a `Segment`. If you don't want to sample that particular request path, create [Segment](https://github.com/aws/aws-xray-sdk-dotnet/blob/bdb7471e2f14fc58da591321f08b3979729f0eb2/sdk/src/Core/AWSXRayRecorderImpl.cs#L146) with Sampling Response instance member: SampleDecision set to not sampled. 

2. You can set `ContextMissingStrategy` to `LOG_ERROR` and this error won't show up.


#### Long term solution
Currently, `AWSSDKHandler.RegisterXRayForAllServices();` registers all AWS SDK clients in the application and `AWSSDKHandler.RegisterXRay<IAmazonDynamoDB>();` registers all instances of same type (DynamoDb here).  I think, we should add API on `AWSSDKHandler` to do per client instrumentation so instead of registering all clients, it gives flexibility of choosing clients.

**Comment by okubiak** [comment]
Yes, you're right. The best solution is probably to be able to register specific service instances instead of all instances of a service type.

Thank you I'm closing this issue.
