### ISSUE TITLE
ASP.NET Core 2.0 not recording correct status code for request in XRay

### ISSUE THREAD

**Issue by PaulDMendoza** [aws/aws-xray-sdk-dotnet#7]
Problem: When a request throws an exception and returns a 500 type response to the user, the ASP.NET XRay middleware is telling XRay that the whole request was a 200 even though one of the subsegments has an error. This makes searching for problems more difficult in XRay. Notice the search result says there were no faults or errors but there should have been one faulting request. 

Issue 2 but maybe related: It seems like there are two segments in the XRay trace instead of just one. My understanding it there should be just one but I could be confused on that. The documentation you guys wrote says not to define new Segments if the app is running in a Lambda because a segment is already generated for us. 

![image](https://user-images.githubusercontent.com/1039795/36288562-22e62b14-1270-11e8-8a2e-90cf22d1852f.png)

![image](https://user-images.githubusercontent.com/1039795/36288546-042bfdfc-1270-11e8-8a21-56ab6a767e46.png)

You can see how the requests all look good when they really aren't. 

![image](https://user-images.githubusercontent.com/1039795/36288706-e34a722a-1270-11e8-9d6a-b8605da3232f.png)
 
Environment
ASP.NET Core 2.0 application
Running in AWS Lambda

**Comment by yogiraj07** [comment]
Hi @PaulDMendoza,
 
Thank you for your post. Just a nit-pick, ASP.NET Core X-Ray middleware is used in this scenario. 
 
Issue 1:
Though ASP.NET Core is returning 500, from Lambda’s perspective, it has successfully invoked function and hence Lambda node shows green color with status 200.
 
Currently AWS Lambda emits the trace segments on your behalf and does not allow modification of these segments from within the Lambda worker. Hence, the X-Ray SDK is unable to modify this status code if desired.
 
Please refer : https://docs.aws.amazon.com/xray/latest/devguide/xray-services-lambda.html and https://docs.aws.amazon.com/lambda/latest/dg/lambda-x-ray.html
 
In case you are interested in finding such specific response, you can try annotations on subsegment : https://github.com/aws/aws-xray-sdk-dotnet/tree/master#adding-metadataannotations-net-and-net-core
 
Issue 2:
The git readme documentation says AWS Lambda creates segment for us which is available in TraceContext. You can only create subsegments in Lambda function, which X-Ray  internally links  to parent segment created by AWS Lambda.
 
You see 2 separate segments for AWS Lambda  by design. Please refer : https://docs.aws.amazon.com/lambda/latest/dg/lambda-x-ray.html
 
We appreciate your efforts for reporting this scenario.
 
Best,
Yogi

**Comment by PaulDMendoza** [comment]
Thanks Yogi. That's a bit frustrating to hear about XRay reporting the less interesting status codes. 

I will close this issue.

**Comment by dgard1981** [comment]
Four years later and this behaviour is still the same. Will it ever be addressed, as it's kind of pointless to record a trace for a non-200 response when the tracing tool reports it as 200.

**Comment by seekingtheoptimal** [comment]
I am using regular .NET Core app in EBS, so no lambda involved, and X-Ray still reporting everything as 200 HTTP. This is bullshit.
